### ISSUE TITLE
can't install whirlpool in python.

### ISSUE THREAD

**Issue by DeepanjanaD** [oohlaf/python-whirlpool#8]
pywhirlpool.c
      whirlpool/pywhirlpool.c(411): error C2106: '=': left operand must be l-value
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
      [end of output]

What exactly is this error and how do I resolve this

**Comment by oohlaf** [comment]
Hi, this got introduced in Python 3.11 (and for a short while in Python 3.10, but got reverted as it broke many cpython code). The reason is described in https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-c-api-porting.
I've ported the code and should work now in master again.

**Comment by DeepanjanaD** [comment]
Thank You!

**Comment by dragomang87** [comment]
Hi, https://pypi.org/project/Whirlpool/ does not include this update so the AUR package https://aur.archlinux.org/packages/python-whirlpool still fails to compile because of this problem
